spring:
  application:
    name: employee-management

  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
