spring.application.name=employee-management
spring.datasource.url=${DB_URL_MINI_PROJECT}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
